//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace drawwin {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ui_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ui_zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("drawwin.ui_zh_CN", typeof(ui_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 置顶 的本地化字符串。
        /// </summary>
        internal static string aot {
            get {
                return ResourceManager.GetString("aot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夜间模式 的本地化字符串。
        /// </summary>
        internal static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源管理器 的本地化字符串。
        /// </summary>
        internal static string explorer {
            get {
                return ResourceManager.GetString("explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤选项 的本地化字符串。
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程不包含(;分隔) 的本地化字符串。
        /// </summary>
        internal static string nameExclude {
            get {
                return ResourceManager.GetString("nameExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 穿透 的本地化字符串。
        /// </summary>
        internal static string pen {
            get {
                return ResourceManager.GetString("pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新进程列表 的本地化字符串。
        /// </summary>
        internal static string rfb {
            get {
                return ResourceManager.GetString("rfb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题包含 的本地化字符串。
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题不包含(;分隔) 的本地化字符串。
        /// </summary>
        internal static string titleExclude {
            get {
                return ResourceManager.GetString("titleExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度低于 的本地化字符串。
        /// </summary>
        internal static string titleLimit {
            get {
                return ResourceManager.GetString("titleLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明度 的本地化字符串。
        /// </summary>
        internal static string trn {
            get {
                return ResourceManager.GetString("trn", resourceCulture);
            }
        }
    }
}
